### PR TITLE
Hotfix/linuxwrite64

### LINKED ISSUE #173: Empty /etc/passwd after auto escalation
## Bug Description
Pwncat cleared the /etc/passwd file

## pwncat version

```
$ pwncat --version
0.4.3
```

## Target System (aka "victim")
Peak Hill

## Steps to Reproduce
Using `gASVLQAAAAAAAACMBXBvc2l4lIwGc3lzdGVtlJOUjBJjaG1vZCArcyAvYmluL2Jhc2iUhZRSlC4=` as payload for the privesc located at /opt/peak_hill_farm/peak_hill_farm we make the bash file a suid.

Then we run on local shell `run enumerate.gather clear=True` to clear our local cache to enable auto escalation.
Afterwards we run `run enumerate.gather` to try and get the suid file in pwncat's cache
Running `escalate list` gives the following:
```
- add user using file write as root via /bin/bash (SUID) from root (linux.enumerate.file.suid)      
- shell as root via /bin/bash (SUID) from root (linux.enumerate.file.suid)                          
- implant: Private key owned by dill at /home/dill/.ssh/id_rsa                                      - implant: Private key owned by root at /root/.ssh/id_rsa
```

This would suggest we are able to get a root shell. Thus we run `escalate run` resulting in an empty /etc/passwd

## Expected Behavior
For it to give me root bash shell and not clear out the /etc/passwd file

I think adding a priority to a route to root would be helpful. I think it goes down the list in order, however getting a shell through bash would be much easier and less noisy than getting it through a new user via writing to /etc/passwd. Thus "shell as root via /bin/bash" should be higher priority than "add user using file write as root"

## Screenshot
Don't have a screenshot but I did this live on twitch vod is here:
https://www.twitch.tv/videos/1109027911?t=03h33m34s

### PR DESCRIPTION
**Pull request by WesVleuten**
## Description of Changes

Fixes #173.

## Major Changes Implemented:
- Fixed base64 stream in `LinuxWriter`

## Pre-Merge Tasks
- [x] Formatted all modified files w/ `python-black`
- [x] Sorted imports for modified files w/ `isort`
- [x] Ran `flake8` on repo, and fixed any new problems w/ modified files
- [x] Ran `pytest` test cases
- [x] Added brief summary of updates to CHANGELOG (under `[Unreleased]`)

> There are currently issues with the pytest test cases in master. This PR does not affect the results

### CODE REVIEW

**Comment by calebstewart** [comment]
Interestingly, I thought I had gone through and removed the base64-based streams from the GTFObins database, but I apparently did not. That is my bad. This was mainly needed before I could figure out how to send raw data without messing up the terminal.

In order to do this properly, we'd need to have the `base64io` module again, but that required some modifications from public package and therefore used to depend on our internal fork of the repo and this was not ideal at all. We can pull that source directly into pwncat, if needed, but I'll need to do some testing to see what the best path forward is, and I'll get back to you. **Ideally** we just don't need to have base64 streams at all, to be honest.

**Comment by calebstewart** [comment]
I'm going through `gtfobins.json`, and I definitely **did not** remove the base64 payloads. I need to go through individually and make sure that they all have equivalent non-base64 payloads. Once I have that, I'll upload the modified `gtfobins.json` here, and if you could test that, I'd appreciate it.

Long story short, I'd like to not even worry about supporting base64 encoded data transfer options, since it complicates the process, can increase data transfer size, and also doesn't provide any positive benefit anymore (since we can now transmit raw binary data over the TTY w/ the new `LinuxWriter` file-like class).

**Comment by WesVleuten** [comment]
No extra encoding is definitely better. I'm okay closing this PR if you are!

**Comment by calebstewart** [comment]
I'm closing this in favor of #189. It's taking a bit, but I'd like to get tests going for every GTFOBin. Doing that has been a pain.

**Pull request closed without merging**
