### PR TITLE
Upgrade the prompt

### PR DESCRIPTION
**Pull request by pitust**

### CODE REVIEW

**Comment by pitust** [comment]
This fixes #54 and switches to dash-nice prompt.

**Comment by calebstewart** [comment]
There was one dangling reference to the old `remote_prefix` variable, and the escape sequences in the prompt needed their own escaping. Aside from that, it looks great! I appreciate the assist on this. I figured there was a better way to do it, but I hadn't looked into it. I tested with a few different shells, and it seems to behave properly. 

You mentioned in your issue for zsh that this doesn't collapse the home directory to tilde, but I'm 100% okay with that. I don't think that's something to get hung up on.

My only question is: in your issue you mention "in dash, this is 99.9% acceptable". What is the 1% that we may be missing? Did you experience some issues? I think if it mostly works then this is still a better solution, but I just want to be aware of any potential problems.

**Comment by pitust** [comment]
`~` isn't replaced because there is no (as far as I can tell) standard-compliant way to replace stuff in shells.

**Comment by pitust** [comment]
And it leaves all shells with the same solution.

**Comment by calebstewart** [comment]
Okay, if that's the only downside them I'm completely okay with merging. Thanks again!

**Comment by pitust** [comment]
just saying, no shell now collapsese to tilde.

**Comment by calebstewart** [comment]
I personally don't think that's a big deal. Do you?

**Comment by pitust** [comment]
No, that's why I decided to go ahead and not try to fix it (maybe there is some way? I don't know.)

**Pull request merged**
